# Generated by Django 4.2.3 on 2023-08-15 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_restaurant_average_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='restaurant_name',
            new_name='restaurant',
        ),
    ]
